services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${CONTRA_BD}
    ports:
      - 3306:3306
  flask:
    build:
      context: .
      dockerfile_inline: |
        FROM python:alpine
        ENV PYTHONDONTWRITEBYTECODE=1
        ENV PYTHONUNBUFFERED=1
        RUN apk update && apk upgrade && \
            apk add --no-cache mariadb-connector-c && \
            apk add --no-cache --virtual .build-deps gcc musl-dev mariadb-connector-c-dev && \
            pip install Flask mariadb --no-cache-dir && \
            apk --purge del .build-deps
        WORKDIR /srv/src
        CMD flask run --host=0.0.0.0
    restart: always
    volumes:
      - "./src:/srv/src"
    ports:
      - 5000:5000
