services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: contra
    volumes:
      - "./db.sql:/docker-entrypoint-initdb.d/db.sql"
    ports:
      - 3306:3306
  flask:
    build:
      context: .
      dockerfile_inline: |
        FROM python:alpine
        ENV PYTHONDONTWRITEBYTECODE=1
        ENV PYTHONUNBUFFERED=1
        RUN apk update && apk upgrade && \
            apk add --no-cache mariadb-connector-c && \
            apk add --no-cache --virtual .build-deps gcc musl-dev mariadb-connector-c-dev && \
            pip install Flask mariadb requests --no-cache-dir && \
            apk --purge del .build-deps
        WORKDIR /srv/src
        CMD flask run --host=0.0.0.0
    restart: always
    environment:
      OWM_TOKEN: ${OWM_TOKEN}
    volumes:
      - "./src/servidor:/srv/src"
    ports:
      - 5000:5000
  webserver:
    image: lipanski/docker-static-website:latest
    restart: always
    ports:
      - 3001:3000
    volumes:
      - "./src/cliente:/home/static"
