window.codigos = {
    "200": ["Tormenta", "Tormenta con lluvia ligera"],
    "201": ["Tormenta", "Tormenta con lluvia"],
    "202": ["Tormenta", "Tormenta con lluvia abundante"],
    "210": ["Tormenta", "Tormenta ligera"],
    "211": ["Tormenta"],
    "212": ["Tormenta", "Tormenta abundante"],
    "221": ["Tormenta", "Tormenta violenta"],
    "230": ["Tormenta", "Tormenta con llovizna ligera"],
    "231": ["Tormenta", "Tormenta con llovizna"],
    "232": ["Tormenta", "Tormenta con llovizna abundante"],
    "300": ["Llovizna", "Llovizna ligera"],
    "301": ["Llovizna"],
    "302": ["Llovizna", "Llovizna abundante"],
    "310": ["Llovizna", "Light intensity drizzle rain"],
    "311": ["Llovizna", "Drizzle rain"],
    "312": ["Llovizna", "Heavy intensity drizzle rain"],
    "313": ["Llovizna", "Shower rain and drizzle"],
    "314": ["Llovizna", "Heavy shower rain and drizzle"],
    "321": ["Llovizna", "Shower drizzle"],
    "500": ["Lluvia", "Lluvia ligera"],
    "501": ["Lluvia", "Lluvia moderada"],
    "502": ["Lluvia", "Lluvia intensa"],
    "503": ["Lluvia", "Lluvia muy intensa"],
    "504": ["Lluvia", "Lluvia extrema"],
    "511": ["Lluvia", "Lluvia helada"],
    "520": ["Lluvia", "Chubasco ligero"],
    "521": ["Lluvia", "Chubasco"],
    "522": ["Lluvia", "Chubasco intenso"],
    "531": ["Lluvia", "Chubasco violento"],
    "600": ["Nieve", "Nevada ligera"],
    "601": ["Nieve", "Nevada"],
    "602": ["Nieve", "Nevada abundante"],
    "611": ["Nieve", "Sleet"],
    "612": ["Nieve", "Light shower sleet"],
    "613": ["Nieve", "Shower sleet"],
    "615": ["Nieve", "Light rain and snow"],
    "616": ["Nieve", "Rain and snow"],
    "620": ["Nieve", "Light shower snow"],
    "621": ["Nieve", "Shower snow"],
    "622": ["Nieve", "Heavy shower snow"],
    "701": ["Neblina"],
    "711": ["Humo"],
    "721": ["Bruma"],
    "731": ["Tolvanera"],
    "741": ["Niebla"],
    "751": ["Arena"],
    "761": ["Polvareda"],
    "762": ["Cenizas"],
    "771": ["Borrasca"],
    "781": ["Tornado"],
    "800": ["Despejado"],
    "801": ["Nublado", "Pocas nubes"],
    "802": ["Nublado", "Algunas nubes"],
    "803": ["Nublado", "Muchas nubes"],
    "804": ["Nublado", "Muchísimas nubes"]
}
